### ISSUE TITLE
🐛 Wrap toolbar issue for small breakpoints

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#877] opened 2022-01-20 14:46 UTC
## Describe the bug

The toolbar doesn't seem to properly wrap on multiple lines for small breakpoints.

I would expect the RadioGroup to wrap.

![wrap_toolbar](https://user-images.githubusercontent.com/794579/150361143-43cb3b80-7c70-4016-9c5b-013e9cba0ec0.jpg)

**Comment by fraincs** [comment] 2022-01-26 18:15
The issue is that in order to show that a toolbar can wrap we need a parent with a fixed width (700px here) making this look broken on mobile. This will be fixed with a responsive style prop.

**Closed** 2022-02-03 20:15 UTC
Labels: bug:confirmed
