### ISSUE TITLE
🐛 Seems to be a problem with the last tile size in the "row size" example

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#784] opened 2021-11-23 05:33 UTC
## Describe the bug

I am not sure why the last tile is bigger than the first 2.

![image](https://user-images.githubusercontent.com/794579/142975652-b74a66ff-7f7a-4946-b2fc-ce045a3ab8a2.png)

## Steps to reproduce

[![image](https://user-images.githubusercontent.com/794579/142975652-b74a66ff-7f7a-4946-b2fc-ce045a3ab8a2.png)](https://deploy-preview-779--sg-storybook.netlify.app/?path=/docs/tile--tile#row-size)

**Comment by fraincs** [comment] 2021-11-25 14:10
TileGroup does not enforce a alignment for it's children. I am not sure it's a bug or a feature, most of the time you would think the intended behaviour is that each tile takes the highest height, in some cases this might be not the case. Adding `align-items: stretch` to TileGroup Dom element would make it that the Tiles always stretch.

**Comment by alexasselin008** [comment] 2021-11-25 17:05
@fraincs TileGroup doesn't enforce an alignment, but Group does. thats the issue. I believe TileGroup should force  its tile to all have the same height. I'm just not sure what the right fix is.

Also, while alignItems:stretch seems to fix the issue, we only want to add that property if the orientation is horizontal

**Comment by fraincs** [comment] 2021-12-07 19:33
fixed on https://github.com/gsoft-inc/sg-orbit/releases/tag/22.0.3

**Closed by fraincs** 2021-12-07 19:33 UTC
Labels: bug:confirmed
