### ISSUE TITLE
🐛 Select: End Icon slot missalignment

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#611] opened 2021-05-12 19:38 UTC
When using slot="end-icon" in the Select, the selected key is not correctly aligned

## Describe the bug

![image](https://user-images.githubusercontent.com/234418/118033999-77d5b700-b337-11eb-956b-5ce5ef5d14ca.png)

## Expected results

Using align items Center, the content is correctly aligned.
![image](https://user-images.githubusercontent.com/234418/118034408-f29ed200-b337-11eb-8d96-39051d69c91a.png)

**Comment by patricklafrance** [comment] 2021-05-12 19:51
Hi Laurent,

It looks fine to me, have a look at the following docs example: https://orbit.sharegate.design/?path=/docs/select--default-story#item-end-icon

I believe the problem is because you set the slot on the div element instead of the icon element.

You don't have to wrap an icon in a div

**Comment by patricklafrance** [comment] 2021-05-13 21:38
@LaurentDario could please add additional information or close this issue please?

**Comment by patricklafrance** [comment] 2021-05-20 23:28
Closing since it seems alright and we don't have additional informations.

**Closed by patricklafrance** 2021-05-20 23:28 UTC
Labels: bug:unconfirmed
