### ISSUE TITLE
💡 Storybook: Font size equivalent for sizes

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#988] opened 2022-06-06 16:53 UTC
Text elements (like Heading, Text, Links, etc.) using a `size` props are currently not listing the font-size attached to them. This makes it difficult to pick the right size when given only a font-size in mockups.
There might be an easy way to figure it out but for now the way I do it is to open the Dev tools and check the font size in an element in storybook.

## Problem to solve

Make it easy to find the corresponding `size` to a specific font-size for textual components.

## Idea

It could be useful to add a table of equivalence `size` vs `font-size` in those components. Or if Storybook allows it, add a tooltip or information on the size props in the Props list.

**Comment by fraincs** [comment] 2022-06-07 16:50
Would a table under the size section of the Heading page be enough?

**Comment by LaurentDario** [comment] 2022-06-07 17:19
Definitely, just want to make sure it doesn't mess up the documentation and looks odd.

**Comment by fraincs** [comment] 2022-06-07 19:46
![image](https://user-images.githubusercontent.com/361632/172469050-553b4a98-8c66-4341-8609-d97a15f9f2e4.png)

Should we do the same for components who have a size prop? like Avatar?

**Comment by fraincs** [comment] 2022-06-07 20:47
I meant the dimension of the avatar, lets say you have a 24x24 avatar which size would you pick?

**Comment by fraincs** [comment] 2022-06-08 14:11
After doing a tour of some Figma files, I noticed that in some places designers are not using heading / paragraph components in their UI. This ends up creating the issue where we can't easily tell the size of the Heading as it's not an Heading that is being used but free text (sic). If we update our Heading font / color / line-height etc it won't follow. The problem is mostly there.

Documenting the sizes would work but would be a patch and would not fix the core issue.

**Comment by LaurentDario** [comment] 2022-06-08 14:18
Definitely doesn't address the core problem, but I'm unsure if this problem will be easy to fully address. The core problem relies on user error, a designer forgetting to use the right component, or a developer not knowing where to look for that information.
It's more of a "safety-net" change than addressing the problem, we will need to communicate better that info to devs and designers for that.

**Comment by fraincs** [comment] 2022-06-08 14:25
Totally, although I looked 20 design system and none of them document the sizes of the Headings, I guess we must be doing something wrong.

**Comment by patricklafrance** [comment] 2023-01-23 20:09
Is it something you are still considering to do @fraincs ?

Is it still relevant @LaurentDario ?

**Comment by fraincs** [comment] 2023-01-23 20:21
If it's useful for the Developper experience yes

**Comment by patricklafrance** [comment] 2023-01-23 21:20
Ok, are you planning on doing it soon? It's been idle for 8 months.

**Comment by fraincs** [comment] 2023-01-23 22:22
It was just never a priority and since 20 DS does not have it I was on the one day column. Looks more like a tooling issue to me as Figma can't bundle 3 props into a single name. Hence the issue, this might be a case of can we document better our Figma's and avoid the issue completely? Will hit a designers for his advice.

**Comment by patricklafrance** [comment] 2023-01-24 01:28
Ok cool, my recommendation to close this issue if you don’t see hapenning in a near future.

It could be re-open later if it becomes relevant again.

Closed issue are not deleted.

**Closed** 2023-01-25 21:34 UTC
Labels: idea
