### ISSUE TITLE
Change Dropdown color bar behaviour

### ISSUE THREAD

**Issue by Gcaya** [gsoft-inc/sg-orbit#160] opened 2020-01-29 16:12 UTC
### Describe the bug

Only a selected reason of creation should have a colored vertical bar to it's left. Currently any focused option in the dropdown displays the bar.

### Steps to reproduce

(Write your steps here:)

1. Go on the groups page
2. Open a group in the list
3. Make sure there is no reason of creation selected
4. Click on the EditableLabel to choose a reason of creation
5. Move around with arrow keys

### Expected behavior

Only the currently selected item should display a vertical colored bar. The bar should't move either with which ever option is focused. Plz don't mind the difference between "Internal project" and "Internal collaboration" it should display the same text.
![image](https://user-images.githubusercontent.com/8711024/73372905-efd4b680-4285-11ea-8bfb-422098d4431c.png)

### Actual behavior
![CBcNU8ivsf](https://user-images.githubusercontent.com/8711024/73374413-1f84be00-4288-11ea-9e55-693f07155cd4.gif)

(Write what happened. Please add screenshots!)

**Comment by alexasselin008** [comment] 2020-01-29 16:20
The parameter used for the dropdown are 

```
<Dropdown
        className="small"
        placeholder="Choose a reason of creation"
        open
        selection
        clearable=true
        onChange={handleChange}
        onOpen={handleOpen}
        onClose={handleClose}
        value={value}
        options={options}
        selectOnNavigation={false} 
        selectOnBlur={false}
    />
```

**Comment by patricklafrance** [comment] 2020-01-29 19:07
@fraincs can you confirm with the design team what is the correct behavior please?

**Comment by patricklafrance** [comment] 2020-01-29 19:10
@Gcaya I added "minor" and "blocking" tag to our tags list. Can you please add one of these to your issue based on how quick your issues need to be resolved.

**Comment by patricklafrance** [comment] 2020-02-13 16:52
Did you talk about this with the designers @fraincs ?

**Comment by Gcaya** [comment] 2020-02-14 14:46
No, only with @alexasselin008 who proposed to open this issue.

**Comment by patricklafrance** [comment] 2020-02-14 16:49
Sorry @Gcaya my message was intended to @fraincs since he was supposed to talk to the designers about this particular issue.

**Comment by fraincs** [comment] 2020-02-19 18:56
We agreed with designers, will be fixed on milestone Dropdowns

**Comment by fraincs** [comment] 2020-02-20 15:36
Fixed in https://github.com/gsoft-inc/sg-orbit/pull/201

**Closed by fraincs** 2020-02-20 15:36 UTC
Labels: bug report, minor, validate with design
