### ISSUE TITLE
A Label should have an alternative look

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#297] opened 2020-03-31 19:16 UTC
When there's a need to add a label to say a checkbox a round colored label is too much. We need a way to have a basic label, mostly textual.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/361632/78065845-e89f5700-7361-11ea-98f9-ae58eb6d2e07.png">

### Describe the solution you'd like

Add a _textual_ property that would render a different look including a bar : | along with the content needed, could be numeric or a short text like a single letter.

### Describe alternatives you've considered
Let the consumer set the alternate text themselves. But this is a pattern that is emerging and that we will most likely migrate the current labels to this look where possible.

**Comment by patricklafrance** [comment] 2020-03-31 20:49
It's a dupe of https://github.com/gsoft-inc/sg-orbit/issues/280

**Closed by patricklafrance** 2020-03-31 20:49 UTC
Labels: components, feature request, high priority, theming
